#!/usr/bin/env python3
"""Add a Danish `da:` leaf to the `verification_note` mappings already in
`data/v2/final/**`.

WHY A MIGRATION IS NEEDED AT ALL
--------------------------------
Every one of these notes came from a template in a seed builder, and those
templates now carry Danish. That fixes nothing for the ~9 900 notes already
on disk: absorb GAP-FILLS `verification_note` (`_enrich_final_entry`) rather
than overwriting it, so a note that exists is never re-derived from its
generator. The same property that makes a curated rewrite survive a re-flow
makes a generator change invisible to the existing data. Both halves are
needed — the generator for new coins, this script for the ones that are here.
(Same shape as §9's exclusions: tightening a parser filter never removes a
coin already in the seed.)

WHY NOT RE-EMIT THE FILE
------------------------
`dump_v2_canonical` round-trips only 5 of the 24 final yamls byte-for-byte;
the other 19 come back with different line-wrapping in long folded scalars.
Re-emitting would bury ~30 added lines under thousands of rewrap lines and
make `verify_reflow.py`'s output unreadable. So this edits the raw text and
inserts one folded line per note, leaving every other byte alone.

WHY ONLY `final/`
-----------------
`final/` is what the build renders. The seeds are regenerated by builders
that now emit `da` themselves, so backfilling them would be churn that the
next re-seed produces anyway.

SCOPE
-----
Only the fixed-text template families below, and by default only the eight
entities the Danish page consumes — Danish renders nowhere else. Notes whose
text is interpolated per coin (the Hede overview-row note quotes the index
line; the canonical-fineness notes carry a Müntzfuß name and a Δ) and the
hand-written per-coin notes are NOT translated here: each is its own piece of
prose, and a template cannot stand in for it. They keep falling back to
English, which is what every untranslated surface on that site does today.
The run prints how many notes it left behind, and that number is the point —
it is the remaining work, not a rounding error.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[2]
FINAL = REPO / "data" / "v2" / "final"
FOLD_WIDTH = 200  # lib/yaml_io ruamel_seed profile

# The entities `data/v2/locations/denmark.yml` consumes — the only coins that
# ever render on a Danish page.
DANISH_ENTITIES = [
    "danish_realm", "danish_norway", "royal_holstein", "royal_slesvig",
    "gottorp_duchy", "sonderburg_duchy", "norburg_plon_duchy",
    "glucksburg_duchy",
]

# en → da. Keyed on the ENGLISH text because it is the one language every
# family has and the one the Danish reader currently falls back to. Matching
# is exact on the fully-unfolded scalar: a near-miss must NOT silently pick
# up a note it was not written for.
DA_BY_EN = {
    # build_kmk_seed.py
    "Record from the Royal Coin Cabinet (Nationalmuseet Copenhagen, "
    "api.natmus.dk); the fields are museum-attested. The coinage standard "
    "of this piece is not yet determined.":
        "Post fra Den kgl. Mønt- og Medaillesamling (Nationalmuseet, "
        "København, api.natmus.dk); felterne er dokumenteret af museet. "
        "Møntfoden for dette stykke er endnu ikke bestemt.",
    # build_ikmk_seed.py
    "Record from the Interactive Catalogue of the Münzkabinett Berlin "
    "(ikmk.smb.museum, CC BY-SA 4.0); the fields are museum-attested. "
    "The coinage standard of this piece is not yet determined.":
        "Post fra Münzkabinett Berlins interaktive katalog "
        "(ikmk.smb.museum, CC BY-SA 4.0); felterne er dokumenteret af "
        "museet. Møntfoden for dette stykke er endnu ikke bestemt.",
    # build_hede_denmark_seed.py — the non-parameterised branch
    "Hede seed: coinage-standard assignment, phase and per-coin "
    "verification are still outstanding; data lifted directly from "
    "danskmoent.dk.":
        "Hede-seed: tildeling af møntfod og fase samt verifikation af "
        "den enkelte mønt udestår stadig; data er hentet direkte fra "
        "danskmoent.dk.",
    # build_ngc_seed.py
    "NGC seed: World Coin Price Guide, Krause-Mishler-based, successor to "
    "the discontinued NumisMaster. Per-coin verification against primary "
    "sources before promotion.":
        "NGC-seed: World Coin Price Guide, baseret på Krause-Mishler, "
        "efterfølger til det nedlagte NumisMaster. Verifikation af den "
        "enkelte mønt mod primærkilder før optagelse.",
    # build_bruun_denmark_seed.py
    "Data taken from the Bruun auction catalogue (Stack's Bowers, "
    "L. E. Bruun Collection 2024-2026). The gross weight is a "
    "single-specimen value; Bruun gives no fineness, so it follows from "
    "the ordinance specification table in Wilcke 1950. The coinage "
    "standard of this piece is not yet determined.":
        "Data hentet fra Bruun-auktionskatalogen (Stack's Bowers, "
        "L. E. Bruun Collection 2024-2026). Bruttovægten er en "
        "enkeltstyksværdi; Bruun angiver ingen finhed, den følger af "
        "specifikationstabellen for forordningerne hos Wilcke 1950. "
        "Møntfoden for dette stykke er endnu ikke bestemt.",
    # build_numista_seed.py
    "Numista seed: coinage-standard and phase assignment plus per-coin "
    "verification are still outstanding; data taken directly from the HTML "
    "catalog page (en.numista.com). Numista is user-edited; cross-references "
    "(SIEG, Galster, Schou, Fr) must be checked against primary sources "
    "before promotion into curated entries.":
        "Numista-seed: tildeling af møntfod og fase samt verifikation af "
        "den enkelte mønt udestår stadig; data er hentet direkte fra "
        "katalogsiden (en.numista.com). Numista redigeres af brugerne; "
        "krydshenvisningerne (Sieg, Galster, Schou, Fr) skal efterprøves "
        "mod primærkilder før optagelse i kuraterede poster.",
    # build_galster_denmark_seed.py
    "Data taken from the Galster pages on danskmoent.dk; the catalogue "
    "cross-references (Schou, Sieg, Jensen-Skjoldager, Schive and others) "
    "come from the page heading and description block. The coinage "
    "standard of this piece is not yet determined.":
        "Data hentet fra Galster-siderne på danskmoent.dk; "
        "kataloghenvisningerne (Schou, Sieg, Jensen-Skjoldager, Schive "
        "m.fl.) stammer fra sidens overskrift og beskrivelsesblok. "
        "Møntfoden for dette stykke er endnu ikke bestemt.",
    # build_numismaster_seed.py
    "Data from the NumisMaster catalogue (Librios), a commercial "
    "Krause-Mishler work. Not yet checked against the primary sources "
    "(Hede / Sieg / Lange / Wilcke / Schive).":
        "Data fra NumisMaster-kataloget (Librios), et kommercielt "
        "Krause-Mishler-værk. Endnu ikke efterprøvet mod primærkilderne "
        "(Hede / Sieg / Lange / Wilcke / Schive).",
    # build_ucoin_seed.py
    "Data from the user-edited coin catalogue ucoin.net. Not yet checked "
    "against the primary sources (Hede / Sieg / Lange / NumisMaster / "
    "Bruun).":
        "Data fra det brugerredigerede møntkatalog ucoin.net. Endnu ikke "
        "efterprøvet mod primærkilderne (Hede / Sieg / Lange / "
        "NumisMaster / Bruun).",
    "ucoin seed (V1 carry-over): pre-cache V1 curator entry, no cache "
    "backing.":
        "ucoin-seed (V1-overførsel): V1-kuratorpost fra før cachen, uden "
        "cache-dækning.",
    # No live generator emits this one — it is frozen in the data, rewritten
    # in place by rewrite_verification_notes.py (family 5).
    "Coinage-standard assignment and per-coin verification against "
    "Hede / Schön / Bruun are still outstanding.":
        "Tildeling af møntfod og verifikation af den enkelte mønt mod "
        "Hede / Schön / Bruun udestår stadig.",
}

# The emitter shares one mapping object across every coin that carries the
# same generated note, so it writes ONE anchored definition and thousands of
# aliases (`verification_note: *id005`). Editing the definition reaches all of
# them — an alias has no block of its own and is skipped by falling through.
_NOTE_RE = re.compile(r"^(?P<indent>\s*)verification_note:(?: +&\S+)?\s*$")
_LANG_RE = re.compile(r"^(?P<indent>\s*)(?P<lang>de|en|uk|da): (?P<rest>.*)$")


def unfold(first: str, cont: list[str]) -> str:
    """Rebuild a folded YAML scalar into the string it parses to."""
    return yaml.safe_load(
        "v: " + first + "".join("\n  " + c.strip() for c in cont)
    )["v"]


def fold(indent: str, key: str, text: str) -> list[str]:
    """Emit `key: text` folded at FOLD_WIDTH, the way ruamel would.

    Quoted rather than plain when the text would otherwise be ambiguous —
    every Danish string here opens with a letter, but several contain «: »
    inside (`Hede-seed: …`), which forces it.
    """
    if ": " in text or " #" in text or text[:1] in "-?:,[]{}#&*!|>'\"%@`":
        text = "'" + text.replace("'", "''") + "'"
    cont = indent + "  "
    lines, cur = [], f"{indent}{key}: "
    for w in text.split(" "):
        if cur.strip() and len(cur) + len(w) + 1 > FOLD_WIDTH:
            lines.append(cur.rstrip() + " ")
            cur = cont
        cur += w + " "
    lines.append(cur.rstrip())
    return lines


def process(raw: str) -> tuple[str, int, int]:
    """Return (new text, notes given a `da`, notes left without one)."""
    lines = raw.split("\n")
    out: list[str] = []
    added = skipped = 0
    i = 0
    while i < len(lines):
        m = _NOTE_RE.match(lines[i])
        if not m:
            out.append(lines[i])
            i += 1
            continue
        note_indent = m.group("indent")
        out.append(lines[i])
        i += 1
        # Collect the whole mapping: language keys at note_indent + 2, each
        # possibly followed by deeper-indented continuation lines.
        block: list[str] = []
        langs: dict[str, str] = {}
        key = None
        first = ""
        cont: list[str] = []

        def close():
            if key:
                langs[key] = unfold(first, cont)

        while i < len(lines):
            line = lines[i]
            if not line.strip():
                break
            lm = _LANG_RE.match(line)
            if lm and lm.group("indent") == note_indent + "  ":
                close()
                key, first, cont = lm.group("lang"), lm.group("rest"), []
                block.append(line)
                i += 1
                continue
            if key and line.startswith(note_indent + "    "):
                cont.append(line)
                block.append(line)
                i += 1
                continue
            break
        close()
        out.extend(block)
        if not langs:
            continue
        if "da" in langs:
            continue
        da = DA_BY_EN.get(langs.get("en", ""))
        if da is None:
            skipped += 1
            continue
        out.extend(fold(note_indent + "  ", "da", da))
        added += 1
    return "\n".join(out), added, skipped


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--apply", action="store_true",
                    help="write changes (default: dry run)")
    ap.add_argument("--all-entities", action="store_true",
                    help="every final yaml, not only the Danish-page ones")
    args = ap.parse_args()

    if args.all_entities:
        targets = sorted(FINAL.glob("*.yml"))
    else:
        targets = [FINAL / f"{e}.yml" for e in DANISH_ENTITIES]

    total_added = total_skipped = 0
    for path in targets:
        if not path.is_file():
            print(f"  ??  {path.name} — not found")
            continue
        raw = path.read_text(encoding="utf-8")
        new, added, skipped = process(raw)
        total_added += added
        total_skipped += skipped
        if added:
            print(f"  {added:5}  +da   {skipped:4} left   {path.name}")
            # Parse guard: the file must still load, and adding a key must
            # not have changed anything else about it.
            before, after = yaml.safe_load(raw), yaml.safe_load(new)
            _strip_da(after)
            assert before == after, f"{path.name}: the edit changed more than `da`"
            if args.apply:
                path.write_text(new, encoding="utf-8")
        elif skipped:
            print(f"      0  +da   {skipped:4} left   {path.name}")
    print(f"{'applied' if args.apply else 'would add'}: {total_added} Danish "
          f"notes; {total_skipped} left in English "
          f"(per-coin or interpolated prose — not template text)")
    if not args.apply:
        print("(dry run — pass --apply to write)")
    return 0


def _strip_da(doc) -> None:
    """Remove every `da` we just added, so the comparison sees the original."""
    for coin in (doc.get("coins") or []):
        vn = coin.get("verification_note")
        if isinstance(vn, dict):
            vn.pop("da", None)


if __name__ == "__main__":
    sys.exit(main())
