"""Audit declared `first_mint` / `last_mint` anchors in
`data/shared/fuesse.yml` against the actual earliest / latest year of
any coin minted under that fuss in the location data.

Why this exists
---------------
The timeline draws TWO independent kinds of markers per fuss:

1. **Auto-derived coin-year rectangles** — small per-year ticks painted
   in the issuing-entity colour, generated by
   `compute_coin_year_runs()` directly from each coin's `year_first` /
   `year_last` / `year_ranges`. These are 100 % data-driven; nothing
   to audit beyond the coin entries themselves.

2. **Hardcoded fuss-anchor rectangles** — the broader `mint`,
   `status`, `circulation` backdrop rectangles per fuss, defined in
   `fuesse.yml` under `events.{first_mint,last_mint,first_adoption,
   std_end,demonetisation}`. These are NOT auto-derived because they
   carry analytical decisions that a pure min/max query over coins
   cannot capture:

   - One-off Sonderprägungen excluded from the canonical mint period
     (e.g. KM#105 1683 Christian V Speciedaler — struck 58 years after
     the 9-Thaler-Fuß ceased operating in Holstein).
   - Out-of-Holstein issues that share the standard but should not
     extend the Holstein-scope anchor (e.g. Copenhagen 1668
     Guldkrone).
   - Pre-mint adoption dates predating the first surviving coin.
   - Standards explicitly never adopted in Holstein (kronemont_chr_iv).

This script flags any *un*explained discrepancy so curated anchors do
not silently drift away from the data.

Conventions
-----------
- The `anywhere` scope covers HRRDN + Scandinavia broadly and is not
  derivable from project data — only the `holstein` scope is checked.
- `danish_realm` issuing entity = Copenhagen-mint coinage; included in
  an informational ⓘ line but NOT used as a "Holstein-mint" data point.
- Discrepancies that match an existing `note:` field on the same event
  are still printed but treated as expected (not counted as issues).

Usage
-----
    .venv/bin/python scripts/audit_fuss_anchors.py
    .venv/bin/python scripts/audit_fuss_anchors.py --location schleswig
"""
from __future__ import annotations
import argparse
from pathlib import Path
import yaml

ROOT = Path(__file__).resolve().parent.parent

# Issuing entities considered "Holstein-mint" for the anchor scope.
# danish_realm is Copenhagen-issued and explicitly excluded — it
# circulated in Holstein but is not a Holstein mint event.
HOLSTEIN_ENTITIES = {
    "royal_holstein", "gottorp_duchy", "gesamtstaat",
    "schauenburg_pinneberg", "sonderburg_duchy",
    "norburg_plon_duchy", "provisional_govt",
}


def load(path: Path):
    with open(path, encoding="utf-8") as f:
        return yaml.safe_load(f)


def collect_years(coins: list[dict]) -> tuple[dict[str, list[int]], dict[str, list[int]]]:
    """Return (holstein_only_years, all_years) per fuss id."""
    by_fuss_holstein: dict[str, list[int]] = {}
    by_fuss_all: dict[str, list[int]] = {}
    for c in coins:
        fid = c.get("fuss")
        if not fid:
            continue
        ent = c.get("issuing_entity")
        years: list[int] = []
        if c.get("year_ranges"):
            for f, l in c["year_ranges"]:
                years.extend(range(int(f), int(l) + 1))
        else:
            yf = c.get("year_first")
            yl = c.get("year_last") or yf
            if yf is not None:
                years.extend(range(int(yf), int(yl) + 1))
        if not years:
            continue
        by_fuss_all.setdefault(fid, []).extend(years)
        if ent in HOLSTEIN_ENTITIES:
            by_fuss_holstein.setdefault(fid, []).extend(years)
    return by_fuss_holstein, by_fuss_all


def audit(location: str) -> int:
    fuesse = load(ROOT / "data/shared/fuesse.yml")
    loc = load(ROOT / f"data/locations/{location}.yml")

    by_fuss, by_fuss_all = collect_years(loc.get("coins", []))

    print(f"Auditing fuss-anchor declarations against '{location}' coin data\n")
    print(f"{'fuss':<28} {'decl_first':>10} {'data_first':>10} {'decl_last':>10} {'data_last':>10}  status")
    print("-" * 100)

    issues = 0
    for fid, fuss in fuesse.items():
        if not isinstance(fuss, dict) or "events" not in fuss:
            continue
        events = fuss["events"]
        fm_event = events.get("first_mint") or {}
        lm_event = events.get("last_mint") or {}
        fm = fm_event.get("holstein") if isinstance(fm_event, dict) else None
        lm = lm_event.get("holstein") if isinstance(lm_event, dict) else None
        fm_note = (fm_event.get("note") if isinstance(fm_event, dict) else None) or ""
        lm_note = (lm_event.get("note") if isinstance(lm_event, dict) else None) or ""

        years = sorted(by_fuss.get(fid, []))
        data_first = years[0] if years else None
        data_last = years[-1] if years else None
        all_years = sorted(by_fuss_all.get(fid, []))
        all_first = all_years[0] if all_years else None
        all_last = all_years[-1] if all_years else None

        flags = []
        if fm is not None and data_first is not None and fm > data_first:
            flags.append(f"declared first_mint {fm} > data {data_first}")
        if lm is not None and data_last is not None and lm < data_last:
            # Tolerate mismatch only if the note explicitly mentions the offending coin year.
            if str(data_last) not in lm_note:
                flags.append(f"declared last_mint {lm} < data {data_last}")
        if fm is not None and data_first is not None and fm < data_first - 5:
            if str(data_first) not in fm_note:
                flags.append(f"declared first_mint {fm} ≪ data {data_first} (Δ {data_first - fm}y)")
        if lm is not None and data_last is not None and lm > data_last + 5:
            if str(data_last) not in lm_note:
                flags.append(f"declared last_mint {lm} ≫ data {data_last} (Δ {lm - data_last}y)")

        ext_notes = []
        if data_last is not None and all_last is not None and all_last > data_last:
            ext_notes.append(f"+danish_realm extends to {all_last}")
        if data_first is not None and all_first is not None and all_first < data_first:
            ext_notes.append(f"+danish_realm starts at {all_first}")

        if flags:
            status = "; ".join(flags)
            issues += 1
        else:
            status = "ok"
            if ext_notes:
                status += " ⓘ " + ", ".join(ext_notes)
        print(f"{fid:<28} {str(fm):>10} {str(data_first):>10} {str(lm):>10} {str(data_last):>10}  {status}")

    print(f"\n{issues} fuesse with un-noted mismatch.")
    return issues


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    p.add_argument("--location", default="schleswig",
                   help="Location id under data/locations/ (default: schleswig)")
    args = p.parse_args()
    rc = audit(args.location)
    raise SystemExit(0 if rc == 0 else 0)  # report-only, never fails CI for now


if __name__ == "__main__":
    main()
